### PR TITLE
Revise manuscript per editorial requests

### PR DESCRIPTION
**Pull request by trangdata**
Suggested by eLife editorial in #110.

Work in progress.

### CODE REVIEW

**Comment by trangdata** [comment]
It is a result showing that our method works. One advantage of having this subsection in Methods is that it would allow the reader to focus on the main results and perhaps have a better flow when they read the paper.

**Comment by cgreene** [comment]
@trang1618 works for me!

**Comment by trangdata** [comment]
Ready for review!

**Review by cgreene — APPROVED** [review]
Looking good! 🚀

**Pull request merged**
