### PR TITLE
Fix some references

### PR DESCRIPTION
**Pull request by cgreene**
Not all of the references made the port unscathed. This fixes some of them, I hope.

### CODE REVIEW

**Comment by cgreene** [comment]
Looks like this works. BTW @dhimmel with the new manubot, if a ref fails to parse it no longer breaks the build via github actions.

**Comment by dhimmel** [comment]
> with the new manubot, if a ref fails to parse it no longer breaks the build via github actions.

yeah, i switched the default to not fail on errors to be more like the `pandoc-citeproc` filter. There's a `manubot-fail-on-errors` setting that we can activate if we'd like CI to enforce that all citations are good.

**Comment by cgreene** [comment]
Ahh - I value failing on errors but I guess not everyone would.

**Comment by dhimmel** [comment]
Okay I activated this option in https://github.com/greenelab/iscb-diversity-manuscript/commit/2d3d3d0c5b8017650696b6f379ea4c8e2b7ecbef

**Pull request merged**
