### PR TITLE
update README with published version

### PR DESCRIPTION
**Pull request by dhimmel**
https://doi.org/10.1016/j.cels.2021.07.007

### CODE REVIEW

**Comment by trangdata** [comment]
It seems that the DOI provided [here](https://www.sciencedirect.com/science/article/pii/S2405471221002854) is not registered?

**Comment by dhimmel** [comment]
`10.1016/j.cels.2021.07.007` is registered with Crossref, but resolves to [a URL](https://www.cell.com/cell-systems/retrieve/pii/S2405471221002854?_returnURL=https%3A%2F%2Flinkinghub.elsevier.com%2Fretrieve%2Fpii%2FS2405471221002854%3Fshowall%3Dtrue) that isn't the paper, and instead looks like:

image

**Comment by cgreene** [comment]
This resolves for me now if you want to merge it!

**Comment by dhimmel** [comment]
Weird, I'm still getting the 404 error. Taking a look at the redirect at https://wheregoes.com/trace/20219133645/:

image

**Comment by dhimmel** [comment]
The redirects now appear to be working, see https://wheregoes.com/trace/20219306854/. Remarkably the DOI resolution goes through 18 redirects!

Screenshot from 2021-09-07 08-07-00

**Pull request merged**
