### PR TITLE
Address #57

### LINKED ISSUE #57: R3: "other categories" is used but not defined
> p. 9, Figure 4: The term "other categories" is used but these are never really defined (see previous point).  It would be good to do so, perhaps even in a supplement.

### PR DESCRIPTION
**Pull request by trangdata**
Closes #57.

Specify which regions category O contains.

### CODE REVIEW

**Review by cgreene — COMMENTED** [review]
Do you want to hyperlink to the table?

**Comment by trangdata** [comment]
Do you mean [Table 1](https://greenelab.github.io/iscb-diversity-manuscript/#tbl:example_names)? It currently does not have the O category.

**Comment by cgreene** [comment]
It provides the categories that would show which ones would end up in group O though.

**Comment by trangdata** [comment]
Oh I see. I thought you meant a completely different table.

**Review by cgreene — APPROVED** [review]
Looks good!

**Pull request merged**
